"""empty message

Revision ID: 117f13e578cf
Revises: 5867fab39979
Create Date: 2026-04-21 15:44:15.869603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117f13e578cf'
down_revision = '5867fab39979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_records', schema=None) as batch_op:
        batch_op.alter_column('total_hours',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_records', schema=None) as batch_op:
        batch_op.alter_column('total_hours',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
