"""add chat_messages table

Revision ID: 186627125d04
Revises: 9d407351a454
Create Date: 2026-05-04 13:02:31.101869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186627125d04'
down_revision = '9d407351a454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('sender_role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_employee_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_company_id'))

    op.drop_table('chat_messages')
    # ### end Alembic commands ###
