"""empty message

Revision ID: 203620fa4959
Revises: e15eeab0e733
Create Date: 2026-05-03 13:04:21.013919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '203620fa4959'
down_revision = 'e15eeab0e733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wellness_checks', schema=None) as batch_op:
        batch_op.alter_column('self_reported_mood',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('admin_recommendation',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_wellness_checks_employee_id'), ['employee_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('wellness_checks_employee_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wellness_checks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('wellness_checks_employee_id_fkey'), 'employees', ['employee_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_wellness_checks_employee_id'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('admin_recommendation',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('self_reported_mood',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
