"""add peer_chat_messages table

Revision ID: 56fb7b2fa2d0
Revises: 186627125d04
Create Date: 2026-05-07 17:28:42.991202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56fb7b2fa2d0'
down_revision = '186627125d04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peer_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('peer_chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_peer_chat_messages_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_peer_chat_messages_sender_id'), ['sender_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peer_chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_peer_chat_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_peer_chat_messages_receiver_id'))

    op.drop_table('peer_chat_messages')
    # ### end Alembic commands ###
