"""empty message

Revision ID: 782a25de6d75
Revises: 95121d1d5756
Create Date: 2026-05-01 11:22:25.709995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782a25de6d75'
down_revision = '95121d1d5756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacaciones', schema=None) as batch_op:
        batch_op.drop_column('employee_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
