"""empty message

Revision ID: 88799ba4a9e4
Revises: 
Create Date: 2026-05-03 09:52:33.890747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88799ba4a9e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wellness_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('self_reported_mood', sa.Integer(), nullable=False),
    sa.Column('survey_comment', sa.Text(), nullable=True),
    sa.Column('ai_joy', sa.Float(), nullable=True),
    sa.Column('ai_stress', sa.Float(), nullable=True),
    sa.Column('ai_sadness', sa.Float(), nullable=True),
    sa.Column('ai_calm', sa.Float(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('final_wellness_score', sa.Float(), nullable=True),
    sa.Column('admin_recommendation', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wellness_checks')
    # ### end Alembic commands ###
