"""empty message

Revision ID: 95121d1d5756
Revises: 22c461670b7d
Create Date: 2026-05-01 11:09:49.657939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95121d1d5756'
down_revision = '22c461670b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vacaciones', schema=None) as batch_op:
        batch_op.drop_column('employee_name')

    # ### end Alembic commands ###
