"""empty message

Revision ID: b7f06a415e9a
Revises: 88799ba4a9e4
Create Date: 2026-05-03 10:20:16.569703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f06a415e9a'
down_revision = '88799ba4a9e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('photo_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('ai_joy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ai_stress', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ai_sadness', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ai_calm', sa.Float(), nullable=True))
        batch_op.add_column(
            sa.Column('final_wellness_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('admin_recommendation',
                            sa.String(length=500), nullable=True))

    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'requires_biometrics', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surveys', schema=None) as batch_op:
        batch_op.drop_column('requires_biometrics')

    with op.batch_alter_table('survey_responses', schema=None) as batch_op:
        batch_op.drop_column('admin_recommendation')
        batch_op.drop_column('final_wellness_score')
        batch_op.drop_column('ai_calm')
        batch_op.drop_column('ai_sadness')
        batch_op.drop_column('ai_stress')
        batch_op.drop_column('ai_joy')
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
