"""empty message

Revision ID: d870b6d077e4
Revises: f8d236c75faa
Create Date: 2026-04-20 11:10:23.215101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd870b6d077e4'
down_revision = 'f8d236c75faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('vacations', sa.Integer(), nullable=True),
    sa.Column('taken_vacations', sa.Integer(), nullable=True),
    sa.Column('available_vacations', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacaciones')
    # ### end Alembic commands ###
